from pydantic import BaseModel


class UploadResponse(BaseModel):
    session_id: str
    response: str
    tier: str
    plan_name: str
    expiry_date: str
    active_sessions: int


class ChatRequest(BaseModel):
    # Unique ID for the conversation (e.g., a UUID generated by the client)
    session_id: str
    message: str


class ChatResponse(BaseModel):
    session_id: str
    response: str
    # Optional: Might want to return a truncated history for debugging
    # history_length: int
