from pydantic import BaseModel


class ChatRequest(BaseModel):
    # Unique ID for the conversation (e.g., a UUID generated by the client)
    session_id: str
    message: str


class ChatResponse(BaseModel):
    session_id: str
    response: str
    # Optional: Might want to return a truncated history for debugging
    # history_length: int
